package com.huangyiyang.fruitsvegetablesmall.bean

data class RecommendGoodsBean(var pageNum:Int,
                              var pageSize:Int,
                              var size:Int,
                              var startRow:Int,
                              var endRow:Int,
                              var total:Int,
                              var pages:Int,
                              var list: List<GoodsDetail>,
                              var prePage:Int,
                              var nextPage:Int,
                              var isFirstPage:String,
                              var isLastPage:String,
                              var hasPreviousPage:String,
                              var hasNextPage:String,
                              var navigatePages:Int,
                              var navigatepageNums:List<Int>,
                              var navigateFirstPage:Int,
                              var navigateLastPage:Int,
                              var firstPage:Int,
                              var lastPage:Int)
