package com.huangyiyang.fruitsvegetablesmall.ui.cassification.model

import com.huangyiyang.fruitsvegetablesmall.ui.cassification.contract.ClassificationDetailFragmentContract

class ClassificationDetailFragmentModel : ClassificationDetailFragmentContract.ClassificationDetailFragmentModel{
}